speaker_source_language = "English"
speaker_target_language = "Portuguese"
mic_source_language = "Portuguese"
mic_target_language = "English"
chunk_duration_ms = 500
whisper_model = "small"
tts_speed = 1.100000023841858
loopback_device = "Fone de ouvido do headset (usb audio voice)"
headphones_device = "Fone de ouvido do headset (usb audio voice)"
mic_device = "Microfone do Headset (usb audio voice)"
