speaker_source_language = "Portuguese"
speaker_target_language = "English"
chunk_duration_ms = 300
whisper_model = "small"
tts_speed = 1.1
# input_device = "Microfone do Headset"  # leave empty to use system default
