use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use shared::{Language, PipelineStage, StageError, TextSegment, TranslationDirection};
use std::io::{BufRead, BufReader, Write};
use std::path::PathBuf;
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;
use thiserror::Error;
use tracing;

#[derive(Debug, Error)]
pub enum TranslationError {
    #[error("Translation bridge not started")]
    BridgeNotStarted,

    #[error("Failed to start Python bridge: {0}")]
    BridgeStartFailed(String),

    #[error("Translation request failed: {0}")]
    RequestFailed(String),

    #[error("Invalid response from bridge: {0}")]
    InvalidResponse(String),
}

#[derive(Serialize)]
struct TranslateRequest {
    text: String,
    source_lang: String,
    target_lang: String,
}

#[derive(Deserialize)]
struct StreamingFragment {
    fragment: String,
    is_final: bool,
}

/// One piece of a streaming translation. Multiple fragments make up a
/// full translated utterance. The TTS stage synthesises each fragment
/// independently so audio can start playing while later fragments are
/// still being generated by the LLM.
#[derive(Debug, Clone)]
pub struct TranslationFragment {
    pub text: String,
    /// True for the terminator emitted after the last text fragment.
    /// The terminator's `text` is empty.
    pub is_final: bool,
}

/// Streaming translator backed by the local Qwen 2.5 1.5B Instruct LLM
/// (via `scripts/translation_bridge.py`). Replaces the previous atomic
/// NLLB / CTranslate2 path — see ADR 0009.
///
/// One instance owns a single Python subprocess; the `Mutex` serialises
/// concurrent callers so streaming responses don't interleave on stdout.
/// Clone the `Arc<LlmTranslator>` to share between pipelines.
pub struct LlmTranslator {
    bridge_script_path: PathBuf,
    process: Option<Mutex<BridgeProcess>>,
    direction: TranslationDirection,
}

struct BridgeProcess {
    child: Child,
    stdin: std::process::ChildStdin,
    stdout: BufReader<std::process::ChildStdout>,
}

/// Backwards-compatibility alias. Old `OpusMtTranslator` callers keep
/// compiling; the underlying engine is now Qwen, not Opus-MT.
pub type OpusMtTranslator = LlmTranslator;

impl LlmTranslator {
    pub fn new(bridge_script_path: PathBuf, direction: TranslationDirection) -> Self {
        Self {
            bridge_script_path,
            process: None,
            direction,
        }
    }

    /// Atomic translation — buffers every fragment until the stream
    /// finishes and returns the concatenated result. Kept for callers
    /// that don't care about streaming (e.g. unit tests, debug tools).
    pub fn translate(&self, segment: &TextSegment) -> Result<TextSegment, TranslationError> {
        let mut combined = String::new();
        self.translate_stream(segment, |fragment| {
            if !fragment.is_final {
                combined.push_str(&fragment.text);
            }
        })?;
        Ok(TextSegment::new(combined.trim().to_string(), self.direction.target))
    }

    /// Streaming translation. Calls `on_fragment` for every commit-eligible
    /// piece of the translation as the LLM produces it, plus one final
    /// call with `is_final=true` to mark the end. The closure runs on the
    /// caller's thread (no spawning), so synthesis can start immediately
    /// without an extra channel hop.
    pub fn translate_stream<F>(
        &self,
        segment: &TextSegment,
        mut on_fragment: F,
    ) -> Result<(), TranslationError>
    where
        F: FnMut(&TranslationFragment),
    {
        let process_mutex = self
            .process
            .as_ref()
            .ok_or(TranslationError::BridgeNotStarted)?;

        let mut bridge = process_mutex.lock().map_err(|e| {
            TranslationError::RequestFailed(format!("Lock poisoned: {}", e))
        })?;

        let request = TranslateRequest {
            text: segment.text.clone(),
            source_lang: lang_code(&self.direction.source),
            target_lang: lang_code(&self.direction.target),
        };

        let request_json = serde_json::to_string(&request)
            .map_err(|e| TranslationError::RequestFailed(e.to_string()))?;

        writeln!(bridge.stdin, "{}", request_json)
            .map_err(|e| TranslationError::RequestFailed(e.to_string()))?;
        bridge
            .stdin
            .flush()
            .map_err(|e| TranslationError::RequestFailed(e.to_string()))?;

        // Read fragment lines until is_final=true. The bridge guarantees
        // a terminator even when the model produced nothing, so this
        // loop always exits without blocking forever.
        loop {
            let mut response_line = String::new();
            bridge
                .stdout
                .read_line(&mut response_line)
                .map_err(|e| TranslationError::RequestFailed(e.to_string()))?;

            let parsed: StreamingFragment = serde_json::from_str(response_line.trim())
                .map_err(|e| TranslationError::InvalidResponse(format!(
                    "{}: {}", e, response_line
                )))?;

            let fragment = TranslationFragment {
                text: parsed.fragment,
                is_final: parsed.is_final,
            };
            tracing::trace!("translation fragment: \"{}\" (final={})",
                fragment.text, fragment.is_final);
            on_fragment(&fragment);
            if parsed.is_final {
                return Ok(());
            }
        }
    }
}

fn lang_code(language: &Language) -> String {
    match language {
        Language::English => "en".to_string(),
        Language::Portuguese => "pt".to_string(),
    }
}

#[async_trait]
impl PipelineStage for LlmTranslator {
    fn name(&self) -> &str {
        "qwen-streaming-translation"
    }

    async fn initialize(&mut self) -> Result<(), StageError> {
        let script_path = self.bridge_script_path.to_string_lossy().to_string();
        tracing::info!("Starting translation bridge: {}", script_path);

        let python = shared::find_python();
        let mut child = Command::new(&python)
            .arg(&script_path)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            // Inherit stderr so llama.cpp's load logs and any tracebacks
            // appear in the parent console without a forwarder thread.
            .stderr(Stdio::inherit())
            .spawn()
            .map_err(|e| StageError::NotInitialized(
                format!("Failed to start Python (tried '{}'). Is Python 3.10+ installed and in PATH? Error: {}", python, e)
            ))?;

        let stdin = child.stdin.take().ok_or_else(|| {
            StageError::NotInitialized("Failed to capture stdin".to_string())
        })?;
        let stdout = child.stdout.take().ok_or_else(|| {
            StageError::NotInitialized("Failed to capture stdout".to_string())
        })?;

        let mut reader = BufReader::new(stdout);
        let mut ready_line = String::new();
        reader
            .read_line(&mut ready_line)
            .map_err(|e| StageError::NotInitialized(format!("Bridge startup failed: {}", e)))?;

        if !ready_line.trim().contains("ready") {
            return Err(StageError::NotInitialized(format!(
                "Bridge did not signal ready: {}",
                ready_line
            )));
        }

        self.process = Some(Mutex::new(BridgeProcess {
            child,
            stdin,
            stdout: reader,
        }));

        tracing::info!("Translation bridge ready (Qwen 2.5 1.5B)");
        Ok(())
    }

    async fn shutdown(&mut self) -> Result<(), StageError> {
        if let Some(process_mutex) = self.process.take() {
            if let Ok(mut bridge) = process_mutex.into_inner() {
                let _ = bridge.child.kill();
                let _ = bridge.child.wait();
            }
        }
        tracing::info!("Translation bridge stopped");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lang_code_returns_correct_codes() {
        assert_eq!(lang_code(&Language::English), "en");
        assert_eq!(lang_code(&Language::Portuguese), "pt");
    }

    #[test]
    fn translate_request_serialises_correctly() {
        let request = TranslateRequest {
            text: "hello world".to_string(),
            source_lang: "en".to_string(),
            target_lang: "pt".to_string(),
        };
        let json = serde_json::to_string(&request).unwrap();
        assert!(json.contains("hello world"));
    }

    #[test]
    fn streaming_fragment_deserialises() {
        let json = r#"{"fragment": "Olá,", "is_final": false}"#;
        let f: StreamingFragment = serde_json::from_str(json).unwrap();
        assert_eq!(f.fragment, "Olá,");
        assert!(!f.is_final);
    }

    #[test]
    fn streaming_fragment_terminator_deserialises() {
        let json = r#"{"fragment": "", "is_final": true}"#;
        let f: StreamingFragment = serde_json::from_str(json).unwrap();
        assert_eq!(f.fragment, "");
        assert!(f.is_final);
    }

    #[test]
    fn translator_without_bridge_returns_error() {
        let translator = LlmTranslator::new(
            PathBuf::from("nonexistent.py"),
            TranslationDirection::new(Language::English, Language::Portuguese),
        );
        let segment = TextSegment::new("hello".to_string(), Language::English);
        let result = translator.translate(&segment);
        assert!(result.is_err());
    }
}
